### ISSUE TITLE
Split the cli-code in a separate repository

### ISSUE THREAD

**Issue by b4dnewz** [skepticfx/subquest#12]
As proposed, we should split the cli-code into a dedicated repository which can be optimized and extended with more features (commands) and actions using commander module.

Since most of the users who use it like a node module will never touch the cli code it will reduce the weight of submodule itself and give us the possibility to extend the cli functions more.

**Comment by b4dnewz** [comment]
I made a quick and working cli tool that map inner functions: https://github.com/b4dnewz/subquest-cli

**Comment by b4dnewz** [comment]
@skepticfx can you run a version patch and publish again? 😀 yesterday while testing I fixed a couple of errors and today I'm updating my domain-scanner and I need those fixes. 
thanks in advance!

**Comment by skepticfx** [comment]
@b4dnewz Done! Also added you to the npm package collabs :) Feel free to publish. Lets ping each other for code reviews and ideas
