### ISSUE TITLE
Scan for DNS Zone Transfer

### ISSUE THREAD

**Issue by b4dnewz** [skepticfx/subquest#15]
I'm watching at "rivals", in particular a package called [Knock](https://github.com/guelfoweb/knock), which looks cool and promising, made by a fellow italian :it: guy.

Having said this, we should code and integrate a **DNS Zone Transfer** scan in subquest module, it should not be too difficult, but I'm already aware of possible issues.

#### The problem:
I'm aware that dns zone transfer could be an issue in node right now based on [#14648](https://github.com/nodejs/node/issues/14648), [#14713](https://github.com/nodejs/node/issues/14713) discussions on node github repository but It can still be done as we can see in [jpenalbae/dns-axfr](https://github.com/jpenalbae/dns-axfr) repository.

#### Proposal:
1. We can use [jpenalbae/dns-axfr](https://github.com/jpenalbae/dns-axfr) module and integrate it in subquest domain scanner for doing AXFR requests (for dns zone transfer)
2. We can take out the best of this module and rewrite a simplified version for the purpose of the project.

#### Extra: 
https://en.wikipedia.org/wiki/DNS_zone_transfer

**Comment by skepticfx** [comment]
I guess option 1 should be the best. Let us make sure we hardcode our version dependency. Not everyone is following semvar properly these days. Recently broke a huge go project due to some inner dependency not keeping the master clean.
