### ISSUE TITLE
Add more dictionary names

### ISSUE THREAD

**Issue by skepticfx** [skepticfx/subquest#3]
staging
git
svn

**Comment by b4dnewz** [comment]
I've an idea for this, I was thinking to integrate Daniel Miessler's SecLists [DNS dictionaries](https://github.com/danielmiessler/SecLists/tree/master/Discovery/DNS) which are well supported and maintained so we don't have to care too much about it.

**Comment by skepticfx** [comment]
@b4dnewz Thats a great list. Lets do this :) 👍
